### ISSUE TITLE
Improperly added delay 

### ISSUE THREAD

**Issue by ozaslan** [ahmetsduru/quadcopter_simulator#7]
https://github.com/ahmetsduru/quadcopter_simulator/blob/b99e3547c4e7605bed792276c67fa716b4358350/src/trajectory_generator.cpp#L90

Why do you wait for x seconds before publishing the next way point? Maybe the consumer (subscriber node) is consuming this faster then the delay, or is extremely slow that it misses some of the messages? Using a service or publishing waypoint all at once might be a better strategy.

**Comment by ahmetsduru** [comment]
ok
